services:
  vpn:
    build: .
    container_name: vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      - VPN_USER=${VPN_USER:-}
      - VPN_PASS=${VPN_PASS:-}
    volumes:
      - ./1757298463444.ovpn:/vpn/vpn.conf.orig:ro
    ports:
      - "1080:1080"
    restart: unless-stopped

  socks5:
    image: serjs/go-socks5-proxy
    container_name: socks5
    network_mode: "service:vpn"
    environment:
      - PROXY_PORT=1080
      - REQUIRE_AUTH=false
    depends_on:
      - vpn
    restart: unless-stopped
